Xms UI rework
OpenLXP/openlxp-xms-ui pull request #5
Opened 2021-05-10 15:26 UTC by schittlur

2021-05-11 13:25 UTC, jdiouf commented on src/components/WelcomeScreen/WelcomeScreen.js
> +      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui ipsum molestiae illum cumque aliquid dolorem veniam iusto facere dolorum architecto maiores recusandae ipsa nihil sapiente eius no
TODO: story to let system operator define this message in the admin console

2021-05-17 17:56 UTC, mattdrayer commented on src/components/Header/Header.js
> +import icon from "../../resources/internal/dodLogo.png";
This will need to be moved to configuration/env-var at some point

2021-05-17 17:56 UTC, mattdrayer commented on src/components/Header/Header.js
> +    subtitle: "Department of Defense",
This will need to be moved out to configuration/env-var at some point

2021-05-17 17:57 UTC, mattdrayer commented on src/components/Header/Header.test.js
> +    screen.getByText("Department of Defense");
This will need to be moved out to configuration/env-var at some point -- need to keep in mind that this software is for anyone to use.

2021-05-17 17:58 UTC, mattdrayer commented on src/components/Header/Header.test.js
> +  test("dose take user to Dashboard when clicking Sign In", () => {
Nit: "dose" -> "does"

2021-05-17 17:59 UTC, mattdrayer commented on src/components/Header/Logo/HeaderLogo.js
> +    <img src={imageToShow} alt="DOD Logo" className={"pl-3"} />
Alt text value needs to be moved out to configuration/env-var at some point

2021-05-17 17:59 UTC, mattdrayer commented on src/components/Header/Logo/HeaderLogo.test.js
> +import img from "../../../resources/internal/dodLogo.png";
This will need to be moved out to configuration/env-var at some point

2021-05-18 19:58 UTC, jdiouf requested changes
Almost there, just need test cases for: Breadcrumbs.js, MainPage.js, and DashboardPage.js
Those components are very basic so I think a test case for each should do it.

2021-05-19 15:19 UTC, rglasgow-deloitte approved these changes

2021-05-19 15:38 UTC, jdiouf approved these changes

2021-05-19 18:13 UTC, merged